"""
Django settings for fileupload project.

Generated by 'django-admin startproject' using Django 1.11.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime
import numpy as np
from numpy import linalg as LA
from urlparse import urljoin
from keras.applications.vgg16 import VGG16
from keras.models import Model
from django.conf import settings

 
#-- load model
start = datetime.datetime.now()
model_base = VGG16(weights='imagenet')
cnn_model = Model(inputs=model_base.input, outputs=model_base.get_layer('fc1').output)
# avoid error
cnn_model.predict( np.zeros((1, 224, 224, 3)) )
end = datetime.datetime.now()
print 'load cnn model: {} secs'.format((end-start).seconds)


#-- model and feature dataset
FEATURE_DATASET_ROOT = os.path.join(settings.BASE_DIR, 'feavct_cc000000')

#-- load feature dataset
imgFea1Ds = None
imgBNs = None
norm_imgFea1Ds = None
imgFea1Ds_list = []
imgBNs_list = []
normImgFea1Ds_list = []

start = datetime.datetime.now()
if FEATURE_DATASET_ROOT :
    pathFeaDS = os.path.split(FEATURE_DATASET_ROOT)[-1]

    for i in range(100) :
        fn_fea = '{}.{}.feas.npy'.format(pathFeaDS, i)
        fn_basename = '{}.{}.bns.npy'.format(pathFeaDS, i)

        path_fea = os.path.join(FEATURE_DATASET_ROOT, fn_fea)
        path_basename = os.path.join(FEATURE_DATASET_ROOT, fn_basename)
     
        if os.path.exists(path_fea) and os.path.exists(path_basename):
            print 'load {} ...'.format(path_fea)
            load_fea = np.load(path_fea)
            imgFea1Ds_list.append(load_fea)

            print 'load {} ...'.format(path_basename)
            load_bn = np.load(path_basename)
            imgBNs_list.append(load_bn)

            #-- norm
            print 'calculate norm of feature vectures ...'
            norm = LA.norm(load_fea, axis=1)
            print norm
            normImgFea1Ds_list.append(norm)
        else:
            break

end = datetime.datetime.now()
print 'load feature dataset: {} secs'.format((end-start).seconds)


FEATURE_IMAGE_URL = urljoin(settings.MEDIA_URL, 'image0000000000/')


