"""
Django settings for fileupload project.

Generated by 'django-admin startproject' using Django 1.11.10.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import datetime
import numpy as np
from urlparse import urljoin
from keras.applications.vgg16 import VGG16
from keras.models import Model
from django.conf import settings

 
#-- load model
start = datetime.datetime.now()
model_base = VGG16(weights='imagenet')
cnn_model = Model(inputs=model_base.input, outputs=model_base.get_layer('fc1').output)
# avoid error
cnn_model.predict( np.zeros((1, 224, 224, 3)) )
end = datetime.datetime.now()
print 'load cnn model: {} secs'.format((end-start).seconds)


#-- load feature dataset
imgFea1Ds = None
imgBNs = None
start = datetime.datetime.now()
if settings.FEATURE_DATASET_ROOT :
    pathFeaDS = settings.FEATURE_DATASET_ROOT

    dirs = os.path.normpath(pathFeaDS).split(os.path.sep)
    bnsFP = os.path.join(pathFeaDS, dirs[-1] + '.bns.npy')
    feasFP = os.path.join(pathFeaDS, dirs[-1] + '.feas.npy')
    if os.path.exists(feasFP) and os.path.exists(bnsFP):
        imgFea1Ds = np.load(feasFP)
        imgBNs = np.load(bnsFP)
    else:
        print '[ERROR] feature datasets are not found, {} {}'.format(bnsFP, feasFP)
end = datetime.datetime.now()
print 'load feature dataset: {} secs'.format((end-start).seconds)


FEATURE_IMAGE_URL = urljoin(settings.MEDIA_URL, 'image2100000000/')
